services:
  db:
    container_name: db
    image: postgres:16
    restart: always
    volumes:
      - udv_test_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    container_name: app
    image: udv_test_api:0.1
    build: .
    restart: always
    volumes:
      - ./src/migrations:/app/src/migrations
    command: >
      sh -c "alembic upgrade head &&
      gunicorn src.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy

volumes:
  udv_test_data: